# docker-compose.yml
version: '3'

services:
 vpnserver:
   build: .
   ports:
       - "1194:1194"
   volumes:
       - ./openvpn-data/conf:/etc/openvpn:z
       - ./openvpn-data/pki:/pki:z
   command: bash -c "runvpn"
   cap_add: 
        - "NET_ADMIN"
   network_mode: "host" 
