#!/bin/bash
firewall-cmd --permanent --add-service openvpn
firewall-cmd --permanent --add-masquerade
firewall-cmd --reload
sysctl -w net.ipv4.ip_forward=1
cat services/doc_openvpn.service | sed "s#{DIR}#$(pwd)#g" > /usr/lib/systemd/system/doc_openvpn.service
